### ISSUE TITLE
Payloadの型がvoidやundefinedの場合、エラーがでます

### ISSUE THREAD

**Issue by kahirokunn** [sue71/vuex-typescript-fsa#4]
Payloadの型がvoidやundefinedの場合、エラーがでます。
エラーメッセージは以下のとおりです。

```
Expected 1-2 arguments, but got 0.
```

使用しているのバージョンは
* tsは3.2.4
* vuex-typescript-fsaは0.1.1

エラーが発生するサンプルコード

```typescript
const userLogin = actionCreator<undefined>('USER_LOGIN')
userLogin() // ここででます
```

```typescript
const userLogin = actionCreator<void>('USER_LOGIN')
userLogin() // ここででます
```

これを回避する方法はございますでしょうか。
よろしくおねがいします！

**Comment by sue71** [comment]
報告ありがとうございます 👍 
https://github.com/sue71/vuex-typescript-fsa/pull/7 にて対応しました
